.\"Manpage for WiCLIpedia"
.SH NAME
wiclipedia \- Command-Line Wikipedia Searcher


.SH SYNOPSIS
$ wiclipedia \[OPTIONS\] QUERY

.SH DESCRIPTION
Wiclipedia is \- as the name states \- a State-of-the-art Wikipedia Search tool for the Command Line.

.SH OPTIONS
**Arguments**:

* `QUERY`: [required]

**Options**:

* `-S, --search`: [default: False]
* `--help`: Show this message and exit.
